spring.application.name=reservas

# ==========================================
# CONFIGURACION DEL SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACION DE LA BASE DE DATOS
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/agenda_sena?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CONFIGURACION DE JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACION DE LOGS (Opcional)
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
